SELECT 
	SUM(CASE WHEN Floor = 1 THEN 1 ELSE 0 END) AS 'Floor1',
	SUM(CASE WHEN Floor = 2 THEN 1 ELSE 0 END) AS 'Floor2',
	SUM(CASE WHEN Floor = 3 THEN 1 ELSE 0 END) AS 'Floor3',
	SUM(CASE WHEN Floor = 4 THEN 1 ELSE 0 END) AS 'Floor4',
	SUM(CASE WHEN Floor = 5 THEN 1 ELSE 0 END) AS 'Floor5',
	SUM(CASE WHEN Floor = 6 THEN 1 ELSE 0 END) AS 'Floor6',
	SUM(CASE WHEN Floor = 7 THEN 1 ELSE 0 END) AS 'Floor7',
	SUM(CASE WHEN Floor = 8 THEN 1 ELSE 0 END) AS 'Floor8'
FROM phoenix_students;